version: '3.9'

services:
  db:
    image: gangstead/postgis:13-3.1-arm
    container_name: db
    network_mode: bridge
    restart: always
    environment:
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: dev
    ports:
      - 5432:5432
    # volumes: 
      # - ./postgresdata:/var/lib/postgresql/data
      # - ./database/database.sql:/docker-entrypoint-initdb.d/1-dbinit.sql